spring:
  application:
    name: employee-personal-service
    admin:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/hrmsEmployeePersonal
    username: root
    password: root
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
  aop:
    auto: true
    proxy-target-class: true
  mvc:
    date-format: dd/MM/yyyy
    favicon:
      enabled: false
  dao:
    exceptiontranslation:
      enabled: true
  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
debug: false
trace: false
logging:
  level:
    root: info