spring:
  application:
    name: gateway-service
    admin:
      enabled: false
  aop:
    auto: true
    proxy-target-class: true
  mvc:
    date-format: dd/MM/yyyy
    favicon:
      enabled: false
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 15
debug: false
trace: false
logging:
  level:
    root: info
    org:
      apache:
        tomcat: INFO
        util: WARN